# Generated by Django 4.1 on 2022-10-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_modify_activity_following_relation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrelation',
            constraint=models.UniqueConstraint(fields=('follower_user', 'following_user'), name='unique_follow_relation'),
        ),
    ]
